### ISSUE TITLE
CustomConfig

### ISSUE THREAD

**Issue by kaliflowerx3** [kaliflowerx3/ZoltriTW#1]
```[00:35:41] [Server thread/ERROR]: Error occurred while enabling ZoltriTWMain v0.0.5 (Is it up to date?)
java.lang.NullPointerException
	at kaliflower.CustomConfig.reloadPronounsConfig(CustomConfig.java:25) ~[?:?]
	at kaliflower.CustomConfig.getPronounsConfig(CustomConfig.java:38) ~[?:?]
	at kaliflower.SaveLoad.loadPronouns(SaveLoad.java:22) ~[?:?]
	at kaliflower.ZoltriTWMain.onEnable(ZoltriTWMain.java:21) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]```

**Comment by jakeyray18** [comment]
Should be fixed - https://github.com/kaliflowerx3/ZoltriTW/commit/e8f370db98af233ef26606315d75437c9982b9df
